// scripts/embed-viewer.mjs
//
// Reads viewer.html and writes src/viewer-content.ts as a TS module that
// exports the file content as a string. Used so that bun --compile can
// embed the viewer asset into the standalone binary, and so the runtime
// doesn't need viewer.html on disk.
//
// Run automatically via prepare / pretest / prebuild hooks; can also be
// invoked manually with `pnpm embed-viewer` after editing viewer.html.
//
// When kicadiff is installed as an npm dependency, the user-side install
// runs `prepare` too — but `viewer.html` isn't shipped in the tarball
// (the pre-generated `src/viewer-content.ts` already is). In that case we
// silently no-op so `npm install` doesn't fail.

import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectDir = path.resolve(__dirname, "..");
const viewerPath = path.join(projectDir, "viewer.html");
if (!fs.existsSync(viewerPath)) {
  // Installed as a dependency — viewer.html isn't shipped, but
  // src/viewer-content.ts already is, so there's nothing to regenerate.
  process.exit(0);
}
const viewerHtml = fs.readFileSync(viewerPath, "utf8");

const tsContent = `// AUTO-GENERATED by scripts/embed-viewer.mjs — do not edit by hand.
// Regenerate via \`pnpm embed-viewer\` after changing viewer.html.
//
// This module exists so that:
//  - bun --compile can embed the viewer into a standalone binary
//  - the runtime never needs viewer.html on disk
const VIEWER_HTML = ${JSON.stringify(viewerHtml)};
export default VIEWER_HTML;
`;

fs.writeFileSync(path.join(projectDir, "src/viewer-content.ts"), tsContent);
console.log(`Embedded viewer.html (${viewerHtml.length} bytes) into src/viewer-content.ts`);
