// scripts/embed-viewer.mjs
//
// Reads viewer.html and writes src/viewer-content.ts as a TS module that
// exports the file content as a string. Used so that bun --compile can
// embed the viewer asset into the standalone binary, and so the runtime
// doesn't need viewer.html on disk.
//
// Run automatically via pretest / prebuild hooks; can also be invoked
// manually with `pnpm embed-viewer` after editing viewer.html.

import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectDir = path.resolve(__dirname, "..");
const viewerHtml = fs.readFileSync(path.join(projectDir, "viewer.html"), "utf8");

const tsContent = `// AUTO-GENERATED by scripts/embed-viewer.mjs — do not edit by hand.
// Regenerate via \`pnpm embed-viewer\` after changing viewer.html.
//
// This module exists so that:
//  - bun --compile can embed the viewer into a standalone binary
//  - the runtime never needs viewer.html on disk
const VIEWER_HTML = ${JSON.stringify(viewerHtml)};
export default VIEWER_HTML;
`;

fs.writeFileSync(path.join(projectDir, "src/viewer-content.ts"), tsContent);
console.log(`Embedded viewer.html (${viewerHtml.length} bytes) into src/viewer-content.ts`);
